# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
version: '3.8'
services:
  vote-app:
    image: vote:latest
    build:
      context: ""
      dockerfile: Dockerfile
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://vote-postgresql:5432/vote
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://vote-postgresql:5432/vote
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - "8080:8080"
    depends_on:
      - vote-postgresql
  vote-postgresql:
    image: postgres:14.2
    # volumes:
    #   - ~/volumes/user/vote/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=vote
      - POSTGRES_PASSWORD=vote
      - POSTGRES_HOST_AUTH_METHOD=trust
    # If you want to expose these ports outside your dev PC,
    # remove the "127.0.0.1:" prefix
    ports:
      - 127.0.0.1:5432:5432
